name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t myapi:latest .

      - name: Run Tests
        run: docker run --rm myapi:latest npm test

      - name: Validate OpenAPI Spec
        run: npx swagger-cli validate openapi.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag myapi:latest my-dockerhub-user/myapi:latest
          docker push my-dockerhub-user/myapi:latest

      - name: Deploy via SSH (Staging)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SERVER }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull my-dockerhub-user/myapi:latest
            docker-compose up -d
